version: '3'
services:
  uaa:
    image: gateway-demo-uaa:latest
    container_name: uaa
    expose:
      - "8090"
    ports:
      - "8090:8090"
  secured-service:
    image: gateway-demo-industrial-ref-service:latest
    container_name: industrial-ref
    expose:
      - "9000"
  gateway:
    image: gateway-demo-gateway:latest
    container_name: gateway
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - secured-service
      - uaa